### ISSUE TITLE
Discross not loading messages

### ISSUE THREAD

**Issue by OliverSakic** [Heath123/discross#23]
Hi, discross is not loading the message text and the user profile pictures anymore. Can you please look into this?

![afbeelding](https://user-images.githubusercontent.com/83336979/230450588-8e3b0301-4c72-454c-9781-a5592f5c9a19.png)

**Comment by Heath123** [comment]
Is this the one hosted by RiiConnect24? I haven't been running my version for a few months/years

**Comment by OliverSakic** [comment]
> Is this the one hosted by RiiConnect24? I haven't been running my version for a few months/years

Yes. I didn't know that you don't host that, because on RiiConnect24 it links to this github page...

**Comment by larsenv** [comment]
I removed the feature because Discord said it's not allowed.

**Comment by larsenv** [comment]
The message issue's fixed and I removed the profile picture feature because Discord said it's not allowed.

**Comment by larsenv** [comment]
The message issue's fixed and I removed the profile picture feature because Discord said it's not allowed.

**Comment by OliverSakic** [comment]
> The message issue's fixed and I removed the profile picture feature because Discord said it's not allowed.

okay thanks
